### ISSUE TITLE
Can't upgrade to v4 from the latest Docker container

### ISSUE THREAD

**Issue by adamshand** [jellyfin/jellyfin-plugin-opds#19]
Hello,

I'm running the latest [official Jellyfin Docker container](https://hub.docker.com/r/jellyfin/jellyfin/) and when I look at my plugins the only available version of the OPDS plugin is v1.  I'd like to upgrade to v4 and check out the new features you've been working on!

I suspect this is because the OPDS plugin targetAbi changed between v1 and v2 of the plugin?

I can't find a newer version of a container to run.  Do you know if there is a newer container somewhere I'm missing?  Or else is it  possible to get a version of the plugin built for 10.7.7?

Many thanks,
Adam.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/130651/157794209-f59f8198-e2ce-4684-823c-34ed39a7ce83.png">

**Comment by crobibero** [comment]
There is the `alpha` tag for Jellyfin, and yes- the plugin targets Jellyfin 10.8

**Comment by adamshand** [comment]
Thanks, that works great.
