### ISSUE TITLE
<title> on feeds is set to "4e3eb3c8f985"

### ISSUE THREAD

**Issue by adamshand** [jellyfin/jellyfin-plugin-opds#20]
Testing v4 authentication with Aldiko on iOS, I noticed that feed name (eg. "Aphabetical Books" or "All") is set to "4e3eb3c8f985".  See screenshots.

The correct name flashes for a moment and then is overwritten.  This doesn't happen with MapleRead (my other iOS OPDS client).

Looking at the feed it appears that `<title>` is being set to this for some reason.

```
❯ https https://xxx:yyy@kiriata.zzz.nz/opds/books/recentlyadded | grep '<title>' | head -3
  <title>4e3eb3c8f985</title>
    <title>The Way of Effortless Mindfulness</title>
    <title>Seeing That Frees</title>

❯ https https://xxx:yyy@kiriata.zzz.nz/opds/genres | grep '<title>' | head -3
  <title>4e3eb3c8f985</title>
    <title>Appropriate Technology</title>
    <title>Bamboo</title>
```
![Screenshot 2022-03-11 at 9 02 00 PM](https://user-images.githubusercontent.com/130651/157827662-e4d9dc8f-66da-4e22-b3d7-48926475c0b4.png)
![Screenshot 2022-03-11 at 9 02 32 PM](https://user-images.githubusercontent.com/130651/157827683-5fb72cc2-581b-4c21-aec2-6c768f474b98.png)

**Comment by crobibero** [comment]
The plugin uses the Jellyfin "Friendly Name", which is editable on the dashboard

**Comment by adamshand** [comment]
Okay that makes sense.  However wouldn't it be better to use the actual name of the feed (eg. "Favourites" or "Rexcently Read").
