### ISSUE TITLE
Acquisition links incompatible with KyBook 3

### ISSUE THREAD

**Issue by mcoms** [jellyfin/jellyfin-plugin-opds#23]
The popular iOS OPDS client [KyBook 3](http://kybook-reader.com/) refuses to download books from Jellyfin, but will download fine from Calibre's OPDS content server.

iOS returns a MIME type error:
![IMG_61357689D673-1](https://user-images.githubusercontent.com/517837/158034754-8a85058b-b97a-495b-83ea-982cf819a22d.jpeg)

`curl` reports both servers sending the correct MIME type, however Calibre sends the file as an "attachment" (with a `Content-Disposition` header), whereas Jellyfin streams it inline. As fas as I could see the [OPDS spec](https://specs.opds.io/) doesn't have an opinion, but sending the files as an "attachment" may prove compatible with more clients.

```
# Jellyfin OPDS plugin
< HTTP/1.1 200 OK
< Date: Sat, 12 Mar 2022 20:52:28 GMT
< Content-Type: application/epub+zip
< Server: Kestrel
< Content-Length: 1035996
< Last-Modified: Sat, 12 Mar 2022 17:34:06 GMT
< X-Response-Time-ms: 396
```

```
# Calibre Content Server
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Disposition: attachment; filename="test book.epub"; filename*=utf-8''test%20book.epub
< Content-Length: 1036177
< Content-Type: application/epub+zip
< Date: Sat, 12 Mar 2022 20:53:25 GMT
< ETag: "1978996d9342fb71526ca69f51f818a6ee5a4de7"
< Keep-Alive: timeout=120
< Server: calibre 5.38.0
```

Jellyfin Docker image `latest` (`10.7.7`). Plugin version `1.0.0.0`.

I have raised an issue on the client side: https://github.com/kolyvan/kybook/issues/438

**Comment by crobibero** [comment]
I've added what I think is the fix, but I don't have any iOS devices to test with. I've attached the build artifacts if you are able to test for me

**Comment by mcoms** [comment]
Thanks @crobibero, that's perfect.

Tested using Jellyfin `10.8.0-alpha5`:
```sh
docker run --rm -p 8096:8096 -v $(pwd)/media:/media -v $(pwd)/config:/config -v $(pwd)/cache:/cache jellyfin/jellyfin:10.8.0-alpha5
```

Installing OPDS `4.0.0.0` from the repository gives me the same error as before:
![IMG_1335](https://user-images.githubusercontent.com/517837/159102258-21fa4e1e-c5e6-42fe-a768-8e146e969885.jpg)

Installing `5.0.0.0` from your build artefact works and I can download books as expected:
![IMG_1336](https://user-images.githubusercontent.com/517837/159102265-c5222b37-2cfb-4e75-99db-655147b4c278.jpg)

Tested a few books (`.epub`, `.mobi`, `.pdf`), and general browsing of the catalogue, all working fine, so this has fixed it :+1: Thanks!
