### ISSUE TITLE
No clear instructions

### ISSUE THREAD

**Issue by trey7658** [jellyfin/jellyfin-plugin-opds#35]
I cannot find any clear instructions, either on this GitHub page, nor on my server. I think it would be helpful to have a guide on how to get the plugin running.

**Comment by crobibero** [comment]
Where are you stuck? The url the feed is formatted as is listed in the readme.

**Comment by skatelike** [comment]
Just to add to this, i'm getting an XML file when i got to ${baseUrl}/opds
Not sure if it's a jellyfin issue, jellyfin-opds issue or a me issues.

**Comment by crobibero** [comment]
xml is the expected output format. What is the actual issue being experienced?

**Comment by trey7658** [comment]
> Where are you stuck? The url the feed is formatted as is listed in the readme. 

I can get to the page, but I cannot use it (I can, but only slightly)

![PXL_20230823_212358514.jpg](https://github.com/jellyfin/jellyfin-plugin-opds/assets/47907719/a41af9ca-34f5-45c3-8166-6e2004ff626b)

**Comment by crobibero** [comment]
To use the ODPS feed you would plug the url into a reader. 

https://github.com/opds-community/awesome-opds

**Comment by trey7658** [comment]
> To use the ODPS feed you would plug the url into a reader.
> 
> https://github.com/opds-community/awesome-opds

Oh ok, thank you. I will reopen if I have any issues.
